# Generated by Django 3.2.5 on 2021-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='TransactionDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
