# Generated by Django 3.2.5 on 2021-08-09 04:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='path', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
