# Generated by Django 3.2.5 on 2021-08-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
