# Generated by Django 3.2.5 on 2021-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='location',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
