# Generated by Django 3.2.5 on 2021-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
