# Generated by Django 3.2.5 on 2021-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
