# Generated by Django 3.2.5 on 2021-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0002_alter_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
