# Generated by Django 3.2.5 on 2021-08-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0002_auto_20210818_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.CharField(blank=True, choices=[('IT support technician', 'IT support technician'), ('Software developer', 'Software developer'), ('Systems analyst', 'Systems analyst'), ('Computer service and repair technician', 'Computer service and repair technician'), ('Solution architect', 'Solution architect'), ('Network manager', 'Network manager')], max_length=300, null=True),
        ),
    ]
