# Generated by Django 3.2.5 on 2021-08-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0002_alter_jobseeker_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
