# Generated by Django 3.2.5 on 2021-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0003_auto_20210805_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='first_name',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='last_name',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
