# Generated by Django 3.2.5 on 2021-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0004_alter_payments_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
