# Generated by Django 3.2.5 on 2021-08-10 13:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0005_alter_payments_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='0725470732', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
