# Generated by Django 3.2.5 on 2021-08-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0005_alter_user_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=20, null=True),
        ),
    ]
