# Generated by Django 3.2.5 on 2021-08-10 13:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0006_alter_payments_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
