# Generated by Django 3.2.5 on 2021-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0006_alter_fileupload_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pdf',
            field=models.FileField(default=1, upload_to='documents/pdfs/'),
            preserve_default=False,
        ),
    ]
