# Generated by Django 3.2.5 on 2021-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0006_alter_payments_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='mpesa_number',
            field=models.CharField(default='254725470732', max_length=14),
            preserve_default=False,
        ),
    ]
