# Generated by Django 3.2.5 on 2021-08-14 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0007_alter_payments_mpesa_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
