# Generated by Django 3.2.5 on 2021-08-14 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Seeking_App', '0008_auto_20210814_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
